### ISSUE TITLE
Running into "array_merge(): Argument #2 is not an array" on re-render

### ISSUE THREAD

**Issue by codyjames** [putyourlightson/craft-sprig#26]
### Describe the bug
Trying to use Sprig with the [mailchimp-subscribe](https://github.com/aelvan/mailchimp-subscribe-craft) plugin. 

### Expected behaviour
The submission works but I think when Sprig tries to re-render it hits an error.

### Screenshots
![Screen Shot 2020-09-10 at 11 48 15 AM](https://user-images.githubusercontent.com/378665/92784840-c885b200-f35b-11ea-9726-e67fc5403851.png)

### Versions
- Plugin version: 1.0.0-beta.13
- Craft version: 3.5.8

Here is what our component looks like:

```
{% set subscribeResponse = 
  mailchimpSubscribe is defined
  and mailchimpSubscribe.action == 'subscribe'
  ? mailchimpSubscribe : null %}

{% if subscribeResponse and subscribeResponse.success %}
  <p>You’ve been subscribed!</button>
{% else %}
  <form
    class="newsletter-form"
    sprig
    s-method="post"
    s-action="mailchimp-subscribe/audience/subscribe">
    {{ csrfInput() }}

    {% if subscribeResponse and not subscribeResponse.success %}
      <p>An error occured: {{ subscribeResponse.message }}</p>
    {% endif %}

    <label for="first_name">First Name</label>
    <input
      type="text"
      name="merge_fields[FNAME]"
      placeholder="First Name"
      {% if subscribeResponse and not subscribeResponse.success %}value="{{ subscribeResponse.values.FNAME ?? '' }}"{% endif %}
      />

    <label for="last_name">Last Name</label>
    <input
      type="text"
      name="merge_fields[LNAME]"
      placeholder="Last Name"
      {% if subscribeResponse and not subscribeResponse.success %}value="{{ subscribeResponse.values.LNAME ?? '' }}"{% endif %}
      />

    <label for="email"{% if subscribeResponse and subscribeResponse.errorCode=='1000' %} class="error"{% endif %}>Email:</label>
    <input
      id="email"
      type="text"
      name="email"
      placeholder="Email"
      {% if subscribeResponse and not subscribeResponse.success %}value="{{ subscribeResponse.values.email ?? '' }}"{% endif %}
      required
      />

    <button type="submit" class="btn">
      Join the Newsletter!¡
    </button>
  </form>
{% endif %}
```

**Comment by bencroker** [comment]
Thanks, this has been fixed in version 1.0.0-beta.14.

**Comment by codyjames** [comment]
@bencroker No luck here. Still getting the same error.

Thanks for helping with this, BTW.

**Comment by bencroker** [comment]
Can you test with https://github.com/putyourlightson/craft-sprig/commit/dbfee5d458cf9bb37166f0c82e19313c201e73fe?

**Comment by codyjames** [comment]
@bencroker We're close! It's working much better except that the response should be returning `mailchimpSubscribe` but it is not.

**Comment by bencroker** [comment]
What does it return?

**Comment by codyjames** [comment]
The mailchimp-subscribe plugin would return `mailchimpSubscribe` to be used like:

```{% set subscribeResponse = mailchimpSubscribe is defined and mailchimpSubscribe.action == 'subscribe' ? mailchimpSubscribe : null %}```

**Comment by bencroker** [comment]
I realise that, what is it returning at the moment?

**Comment by bencroker** [comment]
So it looks like the `SubscribeResponse` attributes will be passed into the Sprig component as template variables, so the following should be available to you:
```
action
success
errorCode
message
values
response
```

**Comment by codyjames** [comment]
Great, I'll try that out! Sorry I couldn't be more helpful in debugging this.

**Comment by codyjames** [comment]
Seems to be working just great. Thanks for your fast response time on this!
